tasks:
  - init: npm install
    command: npm run start

ports:
  - port: 3000
    onOpen: open-browser

vscode:
  extensions:
    - dsznajder.es7-react-js-snippets

    - jpoissonnier.vscode-styled-components

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
